default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Example:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make download'
	@echo
	@echo '	$$ make extract'
	@echo
	@echo '	$$ make install'
	@echo
	@echo '	$$ make iso-download'
	@echo
	@echo '	$$ make update'
	@echo


.PHONY: help



download:
	./download.sh
.PHONY: download


extract:
	./extract.sh
.PHONY: extract

install:
	./install.sh
.PHONY: install

update:
	./update.sh
.PHONY: update


iso-download:
	./iso-download.sh
.PHONY: iso-download
